spring:
  application:
    name: Uber

  # R2DBC PostgreSQL Connection
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/Uber
    username: postgres
    password: root

  cloud:
    gateway:
      routes:
        - id: ride-matching-route
          uri: forward:///  # Routes locally to backend Matchmaker port

          predicates:
            - Path=/api/v1/match/**, /api/v1/drivers/**

          filters:
            - name: CustomRateLimiterFilter
              args:
                limit: 100 # Maximum requests allowed
                windowMillis: 6000 # 60 seconds rolling sliding window

  data:
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          max-active: 64 # Matches default physical thread limits
          max-idle: 32
          min-idle: 8
          max-wait: 2000ms
        shutdown-timeout: 100ms

server:
  port: 8080
  netty:
    connection-timeout: 5000ms
    # WebFlux optimization - limits queue overflow overhead
    max-keep-alive-requests: 10000

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.data.redis: WARN
    # Turn on debugging to see the reactive SQL queries execute in your console
    org.springframework.r2dbc: DEBUG